backend/backend/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.contrib.auth.views import LoginView

from test_endpoint.views import *
from user_management import views as user_views
from . import settings, views

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', user_views.index, name='index')
]

urlpatterns += [
    path('api/test/', get_data)
]

urlpatterns += [
    # Note; since we're not using Angular at the moment,
    # so this is going to use the /flags url. Otherwise we would use /api/flags
    path('users/', include('user_management.urls')),
    path('flags/', include('flag_scoring.urls')),
    path('teams/', include('team_management.urls')),
    path('scores/', include('score_view.urls')),
    path('services/', include('uptime_scoring.urls'))
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Moving away from Angular for the time being for a number of reasons.
# Consult README.
# urlpatterns += [
#     # catch-all pattern for compatibility with Angular routes.
#     # This must be last in the list.
#     path('', views.index),
#     re_path(r'^(?P<path>.*)/$', views.index)
# ]

backend/flag_scoring/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_flags, name='all-flags'),
    path('<int:flag_id>', views.get_flags, name='view-flag'),
    path('add/', views.add_flag, name='add-flag'),
    path('delete/<int:flag_id>', views.delete_flag, name='delete-flag'),
    path('edit/<int:flag_id>', views.edit_flag, name='edit-flag'),
    # path('update/<int:flag_id>', views.update_flag),
    # path('verify/<int:flag_id>/<flag_string>', views.verify_flag,
    path('submit', views.submit_flag, name='submit-flag')
]

urlpatterns += [
]

backend/flag_scoring/models.py
from django.db import models
from team_management.models import Team, TeamMember


class Flag(models.Model):
    """Base class for flags.

    Contains basic attributes that could be extended for different situations later.
    """
    flag_id = models.AutoField(primary_key=True)
    flag_string = models.CharField(max_length=256, blank=False, unique=True)
    value = models.IntegerField(null=False)
    description = models.CharField(max_length=200, blank=False)


class SubmittedFlag(models.Model):
    flag = models.ForeignKey(Flag, on_delete=models.CASCADE)
    team_member = models.ForeignKey(TeamMember, on_delete=models.CASCADE, default=0)
    # submitted_by = models.ForeignKey(Team)

backend/flag_scoring/forms.py
from django import forms
from .models import Flag


class SubmitFlagForm(forms.Form):
    flag_string = forms.CharField(max_length=200, required=True)


class FlagForm(forms.ModelForm):

    class Meta:
        model = Flag
        fields = ('flag_id', 'flag_string', 'description', 'value')

backend/flag_scoring/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404
from django.shortcuts import render, HttpResponse, redirect
from .models import Flag, SubmittedFlag
from score_view.models import ScoringEvent
from .serializers import FlagSerializer
from django.shortcuts import render
from ratelimit.decorators import ratelimit
import config
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .forms import SubmitFlagForm, FlagForm
import logging
log = logging.getLogger('app')


@ratelimit(key=config.ratelimit_key, rate=config.ratelimit_rate, block=True)
@login_required()
def submit_flag(request):
    """
    Submit a flag and then invalidate it.
    :param request:
    :return:
    """

    if request.method == "POST":
        form = SubmitFlagForm(request.POST)
        user = request.user
        try:
            team = user.teammember.team
        except Exception as ex:
            log.debug("Error: " + user.username + " does not have a team. ")
            generic_error = "Error: " + user.username + " does not have a team. "
            return render(request, 'flags.html', {'generic_error': generic_error})
        if form.is_valid() and team is not None:
            flag_string = form.cleaned_data.get('flag_string').lstrip().rstrip()
            flag = Flag.objects.filter(flag_string=flag_string).first()

            if flag is None:
                form.errors['flag_string'] = "Invalid flag string. This flag does not exist."
                return render(request, 'flags.html', {'form': form})

            existing_flag = SubmittedFlag.objects.filter(flag__flag_string=flag_string).first()
            if existing_flag is None:

                new_submitted_flag = SubmittedFlag(flag=flag, team_member=user.teammember)
                new_submitted_flag.save()

                # Give the team the score.
                new_scoring_event = ScoringEvent()
                # TODO: use a namedtuple for EVENT_TYPES
                new_scoring_event.event_type = ScoringEvent.EVENT_TYPES[0][0]
                new_scoring_event.description = "Team " + team.team_name + " found flag: " + flag.description
                new_scoring_event.point_value = flag.value
                new_scoring_event.team = team
                new_scoring_event.save()
                team.save()
                return redirect('scoring-event-list')
            else:
                form.errors['flag_string'] = "Flag string has already been submitted"
    else:
        form = SubmitFlagForm()
        flags = [flag for flag in Flag.objects.all()]
    return render(request, 'flags.html', {'form': form, 'flags': flags})


def all_flags(request):
    flags = [flag for flag in Flag.objects.all()]
    return render(request, 'flags.html', {'flags': flags})


@ratelimit(key=config.ratelimit_key, rate=config.ratelimit_rate, block=True)
@api_view(['GET'])
def get_flags(request, flag_id=0):
    """
    List all flags
    :param request:
    :return:
    """
    if request.method == "GET":
        if flag_id == 0:
            serializer = FlagSerializer(data=None)
            flags = Flag.objects.all()
            serializer = FlagSerializer(flags, many=True)
            return Response(serializer.data)
        else:
            flag = Flag.objects.filter(flag_id=flag_id).first()
            if flag is not None:
                serializer = FlagSerializer(flag, many=False)
                return Response(serializer.data)
            else:
                return Http404


@login_required
@permission_required('scoring_server.can_do_admin')
def add_flag(request):

    context = {}
    if request.method == "GET":
        form = FlagForm()
        context['form'] = form

    if request.method == "POST":
        form = FlagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('scoring-event-list')
        else:
            context['form'] = form
    return render(request, 'add-flag.html', context)


@login_required
@permission_required('scoring_server.can_do_admin')
def edit_flag(request, flag_id):
    flag = Flag.objects.filter(flag_id=flag_id).first()
    context = {}
    form = FlagForm()
    if request.method == "POST":
        form = FlagForm(instance=flag, data=request.POST)
        if form.is_valid():

            form.save()
            return redirect('all-flags')

    context['form'] = form
    context['flag'] = flag

    return render(request, 'edit_flag.html', context)


@api_view(['GET'])
def verify_flag(request, flag_id, flag_string):
    """
    Verify that the flag string matches the flag id.

    :param request:
    :param flag_id: The ID of the flag.
    :param flag_string: The flag string supplied by the user.
    :return:
    """
    flag = Flag.objects.filter(flag_id=flag_id).first()

    if flag_string == flag.flag_string:
        return Response({'valid': True})
    else:
        return Response({'valid': False})


def delete_flag(request, flag_id):
    flag = Flag.objects.filter(flag_id=flag_id).first()
    if flag is not None:
        flag.delete()

    return redirect('all-flags')

backend/flag_scoring/templates/add-flag.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h1>Create Flag</h1>
    <form class="form-group standard-form" method="post" action="{{ request.get_path }}">
    {% csrf_token %}
    <div class="form-group d-flex flex-column">
        <label for="id_for_flag_string">Flag String</label>
        <input id="id_for_flag_string" class="form-control" name="flag_string" />
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_for_value">Value</label>
        <input id="id_for_value" type="number" class="form-control" name="value" />
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_for_description">Description</label>
        <input id="id_for_description"  class="form-control" name="description" />
    </div>

    <div class="form-group d-flex flex-column">
        <button id="submit_btn" type="submit" class="btn btn-sm btn-outline-dark">Create</button>
    </div>
    {% if form.errors %}
        <div class="alert alert-danger">
    	{{ form.errors }}
        </div>
    {% endif %}
    </form>
</div>
{% endblock %}

backend/flag_scoring/templates/edit_flag.html
{% extends "base.html" %}


{% block content %}
<div class="container">
	<h1>Edit Flag</h1>
	<h1>Create Flag</h1>
    <form class="form-group standard-form" method="post" action="{{ request.get_path }}">
    {% csrf_token %}
    <div class="form-group d-flex flex-column">
        <label for="id_for_flag_string">Flag String</label>
        <input id="id_for_flag_string" class="form-control" name="flag_string" value="{{ flag.flag_string }}"/>
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_for_value">Value</label>
        <input id="id_for_value" type="number" class="form-control" name="value" value="{{ flag.value }}"/>
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_for_description">Description</label>
        <input id="id_for_description"  class="form-control" name="description" value="{{ flag.description }}"/>
    </div>
        <input type="hidden"  class="form-control" name="flag_id" value="{{ flag.flag_id }}"/>


    <div class="form-group d-flex flex-column">
        <button id="submit_btn" type="submit" class="btn btn-sm btn-outline-dark">Update</button>
    </div>
    {% if form.errors %}
        <div class="alert alert-danger">
    	{{ form.errors }}
        </div>
    {% endif %}
    </form>
</div>
{% endblock %}

backend/flag_scoring/templates/flags.html
{% extends "base.html" %}
{% load static %}
{% block static_files %}
<link href="{% static 'flag_scoring/flag_scoring.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" class="form submit-flag-form">
        {% csrf_token %}
        <div class="form-group d-flex flex-column">
            {{ form.flag_string.label }}
            <input type="text" class="form-control my-2" name="flag_string" maxlength="200" required id="id_flag_string">
        </div>
        <div class="form-group d-flex flex-column">
            <button type="submit" class="btn btn-outline-dark form-control" >Submit</button>
        </div>
        {% if form.errors %}
        <div class="alert-danger">
        {{ form.errors.flag_string }}
        </div>
        {% endif %}
    </form>


    {% if perms.scoring_server.can_do_admin %}
    <table class="table table-striped">
        <tr>
            <th>Flag String</th>
            <th>Value</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    {% for flag in flags %}
        <tr>
            <td>{{ flag.flag_string }}</td>
            <td>{{ flag.value }}</td>
            <td>{{ flag.description }}</td>
            <td><a href="{% url 'edit-flag' flag.flag_id %}" class="btn btn-sm btn-info">Edit</a></td>
            <td><a href="{% url 'delete-flag' flag.flag_id %}" class="btn btn-sm btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
    </table>
    <div class="my-4">
    <a href="{% url 'add-flag' %}" class="btn btn-sm btn-outline-dark">Add Flag</a>

    </div>
    {% endif %}
    {% if generic_error %}
    <div class="alert-danger">
        {{ generic_error }}
    </div>
    {% endif %}
</div>
{% endblock %}