backend/backend/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.contrib.auth.views import LoginView

from test_endpoint.views import *
from user_management import views as user_views
from . import settings, views

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', user_views.index, name='index')
]

urlpatterns += [
    path('api/test/', get_data)
]

urlpatterns += [
    # Note; since we're not using Angular at the moment,
    # so this is going to use the /flags url. Otherwise we would use /api/flags
    path('users/', include('user_management.urls')),
    path('flags/', include('flag_scoring.urls')),
    path('teams/', include('team_management.urls')),
    path('scores/', include('score_view.urls')),
    path('services/', include('uptime_scoring.urls'))
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Moving away from Angular for the time being for a number of reasons.
# Consult README.
# urlpatterns += [
#     # catch-all pattern for compatibility with Angular routes.
#     # This must be last in the list.
#     path('', views.index),
#     re_path(r'^(?P<path>.*)/$', views.index)
# ]

backend/team_management/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('', all_teams, name='all-teams'),
    path('add-team', add_team, name='add-team'),
    path('add-team-member/<int:team_id>', add_team_member, name='add-team-member'),
    path('edit/<int:team_id>', edit_team, name='edit-team'),
    path('delete/<int:team_id>', delete_team, name='delete-team'),
    path('change-team-password/<int:team_id>', change_team_password, name='change-team-password'),
    path('change-user-password', change_user_password, name='change-user-password')
]

backend/team_management/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Team(models.Model):
    """
    Represents one team.

    """
    team_id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=200, null=False, blank=False, unique=True)

    current_score = models.IntegerField(default=0)
    description = models.CharField(max_length=256)
    max_size = models.IntegerField(default=4)
    # TODO: Hash this?
    team_password = models.CharField(max_length=256, default="")

    TEAM_TYPE = [
        ('RT', 'RED_TEAM'),
        ('BT', 'BLUE_TEAM')
    ]
    team_type = models.CharField(max_length=3, choices=TEAM_TYPE)

    def __str__(self):
        return self.team_name


class TeamMember(models.Model):
    """
    Individual team member.

    Also, this is a custom user table that has the following fields rather the fields provided by Django
    out of the box.
    """
    # Add a OneToOne field so it extends the UserModel without much changes.
    # We will probably use a custom UserCreationForm to abstract this away
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    member_name = models.CharField(max_length=200, null=False, blank=False, unique=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

# This makes sure that the TeamMember model will automatically be created when
# we create a user model.


# @receiver(post_save, sender=User)
# def create_team_member(sender, instance, created, **kwargs):
#     if created:
#         TeamMember.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_team_member(sender, instance, **kwargs):
#     instance.team.save()

backend/team_management/forms.py
from django import forms
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import User
from .models import Team


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('team_name', 'team_password', 'description', 'team_type')

    def save(self, commit=True):
        instance = super(TeamForm, self).save(commit=False)
        instance.team_password = make_password(
            instance.team_password , salt=None, hasher='pbkdf2_sha256')
        if commit:
            instance.save()
        return instance


# The reason there are two forms is so that team details can be
# changed without changing the password
class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('team_name', 'description')


class ChangeTeamPasswordForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('team_password', )

    def save(self, commit=True):
        instance = super(ChangeTeamPasswordForm, self).save(commit=False)
        instance.team_password = make_password(
            instance.team_password, salt=None, hasher='pbkdf2_sha256')
        if commit:
            instance.save()
        return instance



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class TeamMemberForm(forms.Form):
    team_id = forms.IntegerField()
    username = forms.CharField(max_length=200, required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(max_length=200, required=True)
    team_password = forms.CharField(max_length=200, required=True)

    def clean(self):
        cleaned_data = super(TeamMemberForm, self).clean()
        team_password = cleaned_data.get('team_password')

        team = Team.objects.filter(team_id=cleaned_data.get('team_id')).first()
        if team is not None and not check_password(team_password, team.team_password):
            self.add_error('team_password', "Team password is wrong.")

        return cleaned_data


class ChangeUserPaswordForm(forms.Form):
    username = forms.CharField(max_length=200, required=True)
    password = forms.CharField(max_length=200, required=True)
    confirm_password = forms.CharField(max_length=200, required=True)

    def clean(self):
        cleaned_data = super(ChangeUserPaswordForm, self).clean()
        if cleaned_data['password'] != cleaned_data['confirm_password']:
            self.add_error('password', "Passwords must match")

        return cleaned_data

backend/team_management/views.py
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from .forms import TeamMemberForm, TeamForm, ChangeUserPaswordForm, UpdateTeamForm, ChangeTeamPasswordForm
from django.contrib.auth.models import User
from .models import Team, TeamMember
from score_view.models import ScoringEvent
import config
from django.contrib.auth.decorators import permission_required, login_required
import logging
log = logging.getLogger('app')


def all_teams(request):
    context = {}
    context['teams'] = [t for t in Team.objects.all()]
    context['team_members'] = {}
    for team in context['teams']:
        context['team_members'][team.team_name] = []
        for team_member in team.teammember_set.all():
            context['team_members'][team.team_name].append(team_member.member_name)
        if team.team_type == 'BT':
            current_team_score = config.blue_team_starting_score + \
                                 sum([ev.point_value for ev in ScoringEvent.objects.filter(team=team)]) \
                                 - sum([ev.point_value for ev in ScoringEvent.objects.filter(team__team_type='RT')])
        else:
            current_team_score = sum([ev.point_value for ev in ScoringEvent.objects.filter(team=team)])
        team.current_score = current_team_score

    return render(request, 'all_teams.html', context)


@login_required()
@permission_required('scoring_server.can_do_admin')
def add_team(request):
    context = {}
    if request.method == "POST":
        team_form = TeamForm(request.POST)
        if team_form.is_valid():
            team_form.save()
            redirect('index')
        context['form'] = team_form
    else:
        form = TeamForm()
        context['form'] = form
    return render(request, 'add_team.html', context)


@login_required()
@permission_required('scoring_server.can_do_admin')
def add_team_member(request, team_id):

    if request.method == "GET":
        context = {}
        team = Team.objects.filter(team_id=team_id).first()
        if team is None:
            context['current_team'] = "Team not found."
        else:
            context['current_team'] = team.team_name
            context['team_id'] = team.team_id

    if request.method == "POST":
        context = {}
        team_member_form = TeamMemberForm(request.POST)
        team = Team.objects.filter(team_id=team_id).first()

        if team_member_form.is_valid():
            new_user = User()
            new_user.username = team_member_form.cleaned_data['username']
            new_user.email = team_member_form.cleaned_data['email']
            # TODO: hash
            new_user.password = make_password(
                team_member_form.cleaned_data['password'], salt=None, hasher='pbkdf2_sha256')
            # Save new user
            if User.objects.filter(username=new_user.username).first() != None:
                team_member_form.add_error("username", "Username already exists")
                context['form'] = team_member_form
                return render(request, 'add_team_member.html', context)

            new_user.save()
            new_team_member = TeamMember()
            new_team_member.user = new_user
            new_team_member.member_name = new_user.username
            new_team_member.team = team
            new_user.teammember = new_team_member

            new_team_member.save()
            try:
                new_team_member.save()
            except Exception as ex:
                log.debug("Error create new team member.")
            return redirect('all-teams')
        else:
            context['current_team'] = team.team_name
            context['team_id'] = team.team_id

        context['form'] = team_member_form

    return render(request, 'add_team_member.html', context)


@login_required()
@permission_required('scoring_server.can_do_admin')
def change_user_password(request):
    context = {}
    form = ChangeUserPaswordForm()
    if request.method == "POST":
        form = ChangeUserPaswordForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(
                username=form.cleaned_data.get('username')).first()
            if user is not None:
                user.password = make_password(form.cleaned_data.get('password'))
                user.save()
                redirect('all-teams')
            else:
                form['errors']['username'] = "Username not found."

    context['form'] = form
    return render(request, 'change_user_password.html', context)


@login_required
@permission_required('scoring_server.can_do_admin')
def edit_team(request, team_id):
    context = {}
    team = Team.objects.filter(team_id=team_id).first()
    form = UpdateTeamForm()
    context['team'] = team
    if request.method == "POST":
        form = UpdateTeamForm(instance=team, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('all-teams')
        context['form'] = form

    return render(request, 'edit_team.html', context)



@login_required
@permission_required('scoring_server.can_do_admin')
def change_team_password(request, team_id):
    context = {}
    team = Team.objects.filter(team_id=team_id).first()
    form = ChangeTeamPasswordForm()
    context['team'] = team
    if request.method == "POST":
        form = ChangeTeamPasswordForm(instance=team, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('all-teams')
        context['form'] = form

    return render(request, 'change_team_password.html', context)



@login_required
@permission_required('scoring_server.can_do_admin')
def delete_team(request, team_id):

    team = Team.objects.filter(team_id=team_id).first()

    if team is not None:
        team.delete()

    return redirect('all-teams')

backend/team_management/templates/add_team.html
{% extends "base_team_management.html" %}

{% load static %}

{% block static_files %}
<link rel="stylesheet" href="{% static 'team_management/team_management.css' %} ">
{% endblock %}

{% block content %}
<div class="container ">
<form method="POST" class="form team-form">
    {% csrf_token %}
    <div class="form-group d-flex flex-column">
        <label for="id_team_name">Team Name:</label>
        <input id="id_team_name" class="form-control" name="team_name" />
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_team_password">Team Password:</label>
        <input type="password" id="id_team_password" class="form-control" name="team_password" />
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_team_description">Team Description:</label>
        <input id="id_team_description" class="form-control" name="description" />
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_team_description">Team Type:</label>
        <select class="form-control" name="team_type">
            <option value="RT">RED TEAM</option>
            <option value="BT">BLUE TEAM</option>
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-sm btn-outline-dark">Save</button>
    </div>
</form>
</div>
{% endblock %}

backend/team_management/templates/add_team_member.html
{% extends "add_team.html" %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Team: {{ current_team }}</h1>
<form method="POST" action="{{ request.get_path }}" class="form team-form d-flex flex-column">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username</label>
        <input class="form-control" id="id_username" name="username" type="username" />
    </div>
    <div class="form-group">
        <label for="id_email">Email</label>
        <input class="form-control" id="id_email" name="email" type="email" />
    </div>
    <div class="form-group">
        <label for="id_password">Your Password:</label>
        <input class="form-control" id="id_password" name="password" type="password" />
    </div>
    <div class="form-group">
        <label for="id_password">Team Password: </label>
        <input class="form-control" id="id_team_password" name="team_password" type="password" />
    </div>
    <input type="hidden" name="team_id" id="id_team_id" value="{{ team_id }}"/>
    <div class="form-group">
        <input class="btn btn-sm btn-outline-dark" type="submit" value="Save">
    </div>
    {% if form.errors %}
    <div class="alert-danger">
        {% for err, values in form.errors.items %}
        <p>{{ values }}</p>
        {% endfor %}
    </div>
    {% endif %}
</form>
</div>
{% endblock %}

backend/team_management/templates/all_teams.html
{% extends "base_team_management.html" %}

{% block content %}
<div class="container">
    <table class="table table-dark">

        <thead>
            <th>Name</th>
            <th>Description</th>
            <th>Current Score</th>
            <th>Type</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
    {% for team in teams %}
        <td>{{ team.team_name }}</td>
        <td>{{ team.description }}</td>
        <td>{{ team.current_score }}</td>
        <td>{{ team.get_team_type_display }}</td>
        {% if perms.scoring_server.can_do_admin %}
            <td><a href="{% url 'add-team-member' team.team_id %}" class="btn btn-sm btn-outline-light">Add Member</a></td>
            <td><a href="{% url 'edit-team' team.team_id %}" class="btn btn-sm btn-info">Edit</a></td>
            <td><a href="{% url 'delete-team' team.team_id %}" class="btn btn-sm btn-danger">Delete</a></td>
        {% endif %}
        </tbody>
    {% endfor %}

    </table>

    {% if perms.scoring_server.can_do_admin %}
        <div>
            <a class="btn btn-outline-primary btn-sm mb-4" href="{% url 'add-team' %}">Add Team</a>
        </div>
        <div>
            <a class="btn btn-outline-primary btn-sm mb-4" href="{% url 'change-user-password' %}">Change user password</a>
        </div>
        {% for team, members in team_members.items %}
            <table class="table table-dark table-striped">
                <tr><th>{{ team }}</th></tr>
                {% for member in members %}
                        <tr>
                            <td>{{ member }} </td>
                        </tr>
                {% endfor %}
                    </tr>
            </table>
        {% endfor %}
        </table>
    {% endif %}

</div>
{% endblock %}

backend/team_management/templates/base_team_management.html
{% extends "base.html" %}

{% load static %}

{% block static_files %}
<link rel="stylesheet" href="{% static 'team_management/team_management.css' %}">
{% endblock %}

backend/team_management/templates/change_team_password.html
{% extends "add_team.html" %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Team: {{ current_team }}</h1>
<form method="POST" class="form team-form d-flex flex-column" action="{% url 'change-team-password' team.team_id">
    {% csrf_token %}
    <p>{{ team.team_name }}</p>
    <div class="form-group">
        <label for="id_password">Password:</label>
        <input class="form-control" id="id_password" name="team_password" type="password" />
    </div>
    <div class="form-group">
        <input class="btn btn-sm btn-outline-dark" type="submit" value="Save">
    </div>
    {% if form.errors %}
    <div class="alert-danger p-2">
       {{ form.errors }}

    </div>
    {% endif %}
</form>
</div>
{% endblock %}

backend/team_management/templates/change_user_password.html
{% extends "add_team.html" %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Team: {{ current_team }}</h1>
<form method="POST" class="form team-form d-flex flex-column">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username</label>
        <input class="form-control" id="id_username" name="username" type="username" />
    </div>
    <div class="form-group">
        <label for="id_password">Your Password:</label>
        <input class="form-control" id="id_password" name="password" type="password" />
    </div>

    <div class="form-group">
        <label for="id_confirm_password">Confirm Password:</label>
        <input class="form-control" id="id_confirm_password" name="confirm_password" type="password" />
    </div>
    <div class="form-group">
        <input class="btn btn-sm btn-outline-dark" type="submit" value="Save">
    </div>
    {% if form.errors %}
    <div class="alert-danger">
        {% for err, values in form.errors.items %}
        <p>{{ values }}</p>
        {% endfor %}
    </div>
    {% endif %}
</form>
</div>
{% endblock %}

backend/team_management/templates/edit_team.html
{% extends "base_team_management.html" %}

{% load static %}

{% block static_files %}
<link rel="stylesheet" href="{% static 'team_management/team_management.css' %} ">
{% endblock %}

{% block content %}
<div class="container ">
<form method="POST" class="form team-form">
    {% csrf_token %}
    <div class="form-group d-flex flex-column">
        <label for="id_team_name">Team Name:</label>
        <input id="id_team_name" class="form-control" name="team_name" value="{{ team.team_name }}"/>
    </div>
    <div class="form-group d-flex flex-column">
        <label for="id_team_description">Team Description:</label>
        <input id="id_team_description" class="form-control" name="description" value="{{ team.team_description }}" />
    </div>
<!--    <div class="form-group d-flex flex-column">-->
<!--        <label for="id_team_description">Team Description:</label>-->
<!--        <select class="form-control" name="team_type">-->
<!--            <option value="RT">RED TEAM</option>-->
<!--            <option value="BT">BLUE TEAM</option>-->
<!--        </select>-->
<!--    </div>-->

    <input type="hidden" value="{{team.team_type }}" name="team_type">
    <input type="hidden" value="{{team.team_id }}" name="team_id">
    <div class="form-group">
        <button type="submit" class="btn btn-sm btn-outline-dark">Save</button>
    </div>
</form>
    <a href="{% url 'change-team-password' team.team_id %}" class='btn btn-sm btn-outline-dark'>Change Password</a>
    {% if form.errors %}
    <div class="alert-danger p-2">
        {{ form.errors }}
    </div>
    {% endif %}
</div>
{% endblock %}